query Todo($todos: TodosInput!) {
  findAll(todos: $todos) {
    title
    description
  }
}

mutation AddTodo($newTodo: NewTodoInput!) {
  addTodo(newTodo: $newTodo) {
    title
    description
  }
}
