query Todos($first: Int, $after: String) {
  todos(first: $first, after: $after) {
    ...paginatedTodos
  }
}

mutation AddTodo($newTodo: NewTodoInput!) {
  addTodo(newTodo: $newTodo) {
    title
    description
  }
}
